---

- name: Configure go-audit, copy config file template.
  template:
    src: go-audit.yaml.j2
    dest: "/etc/go-audit.yaml"
    mode: 0644
    backup: true
  notify: goaudit_restart

- name: Configure service, copy service file template.
  template:
    src: go-audit.service.j2
    dest: "/etc/systemd/system/go-audit.service"
    mode: 0755
    backup: true
  register: service
  notify: goaudit_restart

- name: Ensure systemd is reloaded if go-audit has changed.
  systemd:
    daemon_reload: yes
  when: service.changed

- name: Rnable go-audit systemd service.
  service:
    name: go-audit
    enabled: true
  when: service.changed
