---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
  ssh_connection_options:
    - '-o ControlPath=~/.ansible/cp/%r@%h-%p'
lint:
  name: yamllint
platforms:
  - name: ubuntu16.04
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    box: ubuntu/xenial64
    memory: 1024
    cpus: 1
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--cpuexecutioncap', '50']"
    provision: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - converge
    - lint
    - verify
verifier:
  name: testinfra
  lint:
    name: flake8
